### ISSUE TITLE
incomprehensible error when deploy app and VM template not found

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#108]
try to deploy vcentershell app when template not found on vcenter

**Comment by nahumtimerman** [comment]
File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main

    "__main__", fname, loader, pkg_name)

  File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 72, in _run_code

    exec code in run_globals

  File "C:\Users\nahum-t\AppData\Local\Temp\08cd45dc-864d-46dd-9f5d-0c384211fe02\Deploy.zip\__main__.py", line 11, in <module>

  File "C:\Users\nahum-t\AppData\Local\Temp\08cd45dc-864d-46dd-9f5d-0c384211fe02\Deploy.zip\__main__.py", line 8, in main

  File "C:\Users\nahum-t\AppData\Local\Temp\08cd45dc-864d-46dd-9f5d-0c384211fe02\Deploy.zip\driver.py", line 27, in execute

  File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 4923, in ExecuteCommand

    raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)

qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.



Error description: 14/Jan/2016 14:37:49 DEBUG Folder composed: './logs'



14/Jan/2016 14:37:49 DEBUG Folder composed: './logs'



14/Jan/2016 14:37:49 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: './logs/vCenter.log'



14/Jan/2016 14:37:49 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: './logs/vCenter.log'



14/Jan/2016 14:37:50 INFO Starting new HTTPS connection (1): 192.168.42.110



14/Jan/2016 14:37:50 DEBUG "GET //sdk/vimServiceVersions.xml HTTP/1.1" 200 552



14/Jan/2016 14:37:50 INFO cloning VM...



DEBUG



Traceback (most recent call last):



  File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main



    "__main__", fname, loader, pkg_name)



  File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 72, in _run_code



    exec code in run_globals



  File "C:\Users\nahum-t\AppData\Local\Temp\bea326e7-3290-413c-a5d0-282a5eef5e5d\Deploy From Template.zip\__main__.py", line 51, in <module>



  File "C:\Users\nahum-t\AppData\Local\Temp\bea326e7-3290-413c-a5d0-282a5eef5e5d\Deploy From Template.zip\__main__.py", line 39, in main



  File "C:\Users\nahum-t\AppData\Local\Temp\bea326e7-3290-413c-a5d0-282a5eef5e5d\Deploy From Template.zip\vCenterShell\command_executer.py", line 44, in deploy_from_template



  File "C:\Users\nahum-t\AppData\Local\Temp\bea326e7-3290-413c-a5d0-282a5eef5e5d\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py", line 131, in execute_deploy_from_template



  File "C:\Users\nahum-t\AppData\Local\Temp\bea326e7-3290-413c-a5d0-282a5eef5e5d\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py", line 47, in _deploy_from_template



  File "C:\Users\nahum-t\AppData\Local\Temp\bea326e7-3290-413c-a5d0-282a5eef5e5d\Deploy From Template.zip\common\vcenter\vmomi_service.py", line 390, in clone_vm



AttributeError: 'NoneType' object has no attribute 'Clone'
