### ISSUE TITLE
Connectivity problem in VLAN

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#130]
integration test Resolve_Auto_Vlan_And_Connect_To_VM failed in vCenterShellEndToEndScenario:
Connect VM fails, stack attached:

[vCenterTesting.vCenterShellEndToEndScenario.Resolve_Auto_Vlan_And_Connect_To_VM] Test method vCenterTesting.vCenterShellEndToEndScenario.Resolve_Auto_Vlan_And_Connect_To_VM threw exception: 
System.Exception: Execute Command Failed:
Command execution failed with error: 'Script runner exited with exit code: 1'.
Error description: 21/Jan/2016 11:38:18 DEBUG Executing Connect VM command on vCenter
Traceback (most recent call last):
  File "C:\BuildAgent\work\bcdb540ec2231238\TestResults\buser_BUILDS7 2016-01-21 11_34_01\Out\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\BuildAgent\work\bcdb540ec2231238\TestResults\buser_BUILDS7 2016-01-21 11_34_01\Out\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\BuildAgent\temp\buildTmp\ea8ca648-4201-46c1-8503-fc450ac3bafd\Connect.zip\__main__.py", line 10, in <module>
  File "C:\BuildAgent\temp\buildTmp\ea8ca648-4201-46c1-8503-fc450ac3bafd\Connect.zip\__main__.py", line 6, in main
  File "C:\BuildAgent\temp\buildTmp\ea8ca648-4201-46c1-8503-fc450ac3bafd\Connect.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 41, in connect
  File "C:\BuildAgent\temp\buildTmp\ea8ca648-4201-46c1-8503-fc450ac3bafd\Connect.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 87, in execute_connect_command
  File "C:\BuildAgent\temp\buildTmp\ea8ca648-4201-46c1-8503-fc450ac3bafd\Connect.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 112, in execute_command_on_vcenter_resource_and_passthrough_result
  File "C:\BuildAgent\temp\buildTmp\ea8ca648-4201-46c1-8503-fc450ac3bafd\Connect.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 101, in execute_command_on_vcenter_resource
  File "C:\BuildAgent\work\bcdb540ec2231238\TestResults\buser_BUILDS7 2016-01-21 11_34_01\Out\ExecutionServerForTesting\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 5115, in ExecuteCommand
    raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)
qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.

Error description: 21/Jan/2016 11:38:19 DEBUG Folder composed: 'C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\..\logs'

21/Jan/2016 11:38:19 DEBUG Folder composed: 'C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\..\logs'

21/Jan/2016 11:38:19 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: 'C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\..\logs\vCenterShell_20160121-113819.log'

21/Jan/2016 11:38:19 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: 'C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\..\logs\vCenterShell_20160121-113819.log'

21/Jan/2016 11:38:19 INFO action:START command_name:connect_to_networks

21/Jan/2016 11:38:19 INFO connecting to vcenter: 192.168.42.110

21/Jan/2016 11:38:19 DEBUG connection params: host: 192.168.42.110 username: administrator@vsphere.local port: 443

21/Jan/2016 11:38:19 INFO Starting new HTTPS connection (1): 192.168.42.110

21/Jan/2016 11:38:19 DEBUG "GET //sdk/vimServiceVersions.xml HTTP/1.1" 200 552

21/Jan/2016 11:38:20 INFO connected to vcenter: 192.168.42.110

21/Jan/2016 11:38:20 INFO executing command: connect_to_networks

21/Jan/2016 11:38:20 DEBUG command params: 'vim.ServiceInstance:ServiceInstance',42221414-4a2b-06a2-c117-bc44bc4309e2,[<vCenterShell.vm.dvswitch_connector.VmNetworkMapping object at 0x030A4670>],QualiSB/anetwork

21/Jan/2016 11:38:20 ERROR error has occurred while executing command: connect_to_networks

21/Jan/2016 11:38:20 ERROR 'str' object has no attribute '_moId'

Traceback (most recent call last):

  File "C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\common\wrappers\command_wrapper.py", line 62, in execute_command_with_connection

    results = command(*tuple(command_args))

  File "C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\vCenterShell\commands\connect_dvswitch.py", line 47, in connect_to_networks

    si, vm, mappings, default_network_instance)

  File "C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\vCenterShell\vm\dvswitch_connector.py", line 56, in connect_by_mapping

    return self.virtual_machine_port_group_configurer.connect_vnic_to_networks(vm, request_mapping, default_network)

  File "C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\vCenterShell\vm\portgroup_configurer.py", line 40, in connect_vnic_to_networks

    mapping, vnic_mapping, vm.network, default_network)

  File "C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\vCenterShell\vm\vnic_to_network_mapper.py", line 23, in map_request_to_vnics

    vnic_name = self._find_available_vnic(vnics_to_network_mapping, default_network)

  File "C:\BuildAgent\temp\buildTmp\e9212969-82bd-435e-ba54-d2bd3f0a6f38\Connect VM.zip\vCenterShell\vm\vnic_to_network_mapper.py", line 31, in _find_available_vnic

    if network_name == default_network:

  File "C:\BuildAgent\work\bcdb540ec2231238\TestResults\buser_BUILDS7 2016-01-21 11_34_01\Out\ExecutionServerForTesting\python\2.7.10\lib\site-packages\pyVmomi\VmomiSupport.py", line 464, in __eq__

    return self._moId == other._moId and \

AttributeError: 'str' object has no attribute '_moId'

21/Jan/2016 11:38:20 INFO disconnecting from vcenter: 192.168.42.110

21/Jan/2016 11:38:20 INFO action:END command_name:connect_to_networks

**Comment by nahumtimerman** [comment]
link to tc build: 
http://tc/viewLog.html?buildId=929187&tab=buildResultsDiv&buildTypeId=Trunk_InWork_Shells_VcenterScenariosWithVCenterShell#testNameId518837089138912407

**Comment by nahumtimerman** [comment]
fixed
