### ISSUE TITLE
try to configure vm with 1 nic with 2 vlan services will cause a massive error

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#160]
STR:
execute connect all command on a reservation with vm that have 2 nics and 2 vlans connected to it

Connect All ended with status Failed with error: 01/Feb/2016 16:36:49 DEBUG Connecting 'VLAN Auto' 
01/Feb/2016 16:36:49 DEBUG Executing Connect command on: test_2ea292dd
01/Feb/2016 16:36:56 DEBUG Setting Target Interface to: 00:50:56:a2:4e:4b
01/Feb/2016 16:36:56 DEBUG Connecting 'VLAN Auto' 
01/Feb/2016 16:36:56 DEBUG Executing Connect command on: test_2ea292dd
Traceback (most recent call last):
File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\tomer.a\AppData\Local\Temp\3061695f-7f21-4974-afc1-90e9fc75077e\Connect All.zip\__main__.py", line 10, in <module>
File "C:\Users\tomer.a\AppData\Local\Temp\3061695f-7f21-4974-afc1-90e9fc75077e\Connect All.zip\__main__.py", line 6, in main
File "C:\Users\tomer.a\AppData\Local\Temp\3061695f-7f21-4974-afc1-90e9fc75077e\Connect All.zip\environment_scripts\service\environment.py", line 67, in connect_all
File "C:\Users\tomer.a\AppData\Local\Temp\3061695f-7f21-4974-afc1-90e9fc75077e\Connect All.zip\environment_scripts\service\environment.py", line 88, in _execute_connect_command_on_connected_resource
File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 5127, in ExecuteCommand
raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)
qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.

Error description: 01/Feb/2016 16:36:56 DEBUG Executing Connect VM command on vCenter

<type 'unicode'>

<type 'unicode'>

<type 'unicode'>

<type 'unicode'>

Traceback (most recent call last):

File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main

"__main__", fname, loader, pkg_name)

File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code

exec code in run_globals

File "C:\Users\tomer.a\AppData\Local\Temp\c7d99ce1-8c78-420f-b265-b1a017c961c2\Connect.zip\__main__.py", line 10, in <module>

File "C:\Users\tomer.a\AppData\Local\Temp\c7d99ce1-8c78-420f-b265-b1a017c961c2\Connect.zip\__main__.py", line 6, in main

File "C:\Users\tomer.a\AppData\Local\Temp\c7d99ce1-8c78-420f-b265-b1a017c961c2\Connect.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 41, in connect

File "C:\Users\tomer.a\AppData\Local\Temp\c7d99ce1-8c78-420f-b265-b1a017c961c2\Connect.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 87, in execute_connect_command

File "C:\Users\tomer.a\AppData\Local\Temp\c7d99ce1-8c78-420f-b265-b1a017c961c2\Connect.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 112, in execute_command_on_vcenter_resource_and_passthrough_result

File "C:\Users\tomer.a\AppData\Local\Temp\c7d99ce1-8c78-420f-b265-b1a017c961c2\Connect.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 101, in execute_command_on_vcenter_resource

File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 5127, in ExecuteCommand

raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)

qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.

Error description: 01/Feb/2016 16:36:57 INFO action:START command_name:connect_to_networks

01/Feb/2016 16:36:57 INFO connecting to vcenter: 192.168.42.110

01/Feb/2016 16:36:57 DEBUG connection params: host: 192.168.42.110 username: administrator@vsphere.local port: 443

01/Feb/2016 16:36:57 INFO Starting new HTTPS connection (1): 192.168.42.110

01/Feb/2016 16:36:57 DEBUG "GET //sdk/vimServiceVersions.xml HTTP/1.1" 200 552

01/Feb/2016 16:36:58 INFO connected to vcenter: 192.168.42.110

01/Feb/2016 16:36:58 INFO executing command: connect_to_networks

01/Feb/2016 16:36:58 DEBUG command params: 'vim.ServiceInstance:ServiceInstance',42227f52-8176-7288-cf8e-f83ee4429914,[<vCenterShell.vm.dvswitch_connector.VmNetworkMapping object at 0x02F8FAB0>],QualiSB/anetwork

01/Feb/2016 16:36:58 ERROR error has occurred while executing command: connect_to_networks

01/Feb/2016 16:36:58 ERROR no vnic available

Traceback (most recent call last):

File "C:\Users\tomer.a\AppData\Local\Temp\90d02fc3-c839-4a3b-aef9-2e3ff24897a5\Connect VM.zip\common\wrappers\command_wrapper.py", line 62, in execute_command_with_connection

results = command(*tuple(command_args))

**Comment by doppleware** [comment]
Lets try to catch this error and throw a sane message as is likely to happen a lot

**Comment by razaba** [comment]
@TomerAdmon @doppleware 
this is when using the deprecated "Connect all" command...
do I need to proceed and check it?

**Comment by TomerAdmon** [comment]
We removed the environment command "Connect all" so this bug is not longer relevant.
