### ISSUE TITLE
When user set a not supported vlan id range, he will get massive error message

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#165]
STR
1) add new vlan auto to sandbox
2) set the vlan id to be 9998-9999
3) execute "Auto resolve Vlan" command

Auto Resolve Vlan ended with status Failed with error: <type 'unicode'>
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
Traceback (most recent call last):
File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\tomer.a\AppData\Local\Temp\eb7671db-f4e4-49c6-b73f-aa85817d16db\Auto Resolve Vlan.zip\__main__.py", line 48, in <module>
File "C:\Users\tomer.a\AppData\Local\Temp\eb7671db-f4e4-49c6-b73f-aa85817d16db\Auto Resolve Vlan.zip\__main__.py", line 29, in main
File "C:\Users\tomer.a\AppData\Local\Temp\eb7671db-f4e4-49c6-b73f-aa85817d16db\Auto Resolve Vlan.zip\vlan_service\resolver\provider.py", line 28, in resolve_vlan_auto
File "C:\Users\tomer.a\AppData\Local\Temp\eb7671db-f4e4-49c6-b73f-aa85817d16db\Auto Resolve Vlan.zip\vlan_service\resolver\provider.py", line 69, in _get_requested_vlan_auto
ValueError: Vlan range is not supported

**Comment by alexazarh** [comment]
Its not a bug. Range is currently not supported as input in Vlan Id :)
