### ISSUE TITLE
Enormous error appears whenever the deployed app fails

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#253]
The failure can be due to the failure of a refresh IP (which triggered automatically ) , terminate the deploy command or any other fail in the process

**Comment by Yairzeri** [comment]
This error appears when the credentials are incorrect:
Deploy App ended with status Failed with error: 29/Feb/2016 09:25:31 INFO Executing 'vCenter VM From Template' on app 'VM Deployment'...
29/Feb/2016 09:25:56 ERROR Error deploying app VM Deployment. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Error>Script runner exited with exit code: 1: Traceback (most recent call last):&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main&#xD;
"__main__", fname, loader, pkg_name)&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code&#xD;
exec code in run_globals&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\6d1d416c-bf13-43cd-abe7-74c58e9cb792\Deploy.zip\__main__.py", line 13, in &lt;module&gt;&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\6d1d416c-bf13-43cd-abe7-74c58e9cb792\Deploy.zip\__main__.py", line 10, in main&#xD;
Error deploying app VM Deployment. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Error>Script runner exited with exit code: 1: Traceback (most recent call last):&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main&#xD;
"__main__", fname, loader, pkg_name)&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code&#xD;
exec code in run_globals&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\6d1d416c-bf13-43cd-abe7-74c58e9cb792\Deploy.zip\__main__.py", line 13, in &lt;module&gt;&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\6d1d416c-bf13-43cd-abe7-74c58e9cb792\Deploy.zip\__main__.py", line 10, in main&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\6d1d416c-bf13-43cd-abe7-74c58e9cb792\Deploy.zip\driver.py", line 34, in execute&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 5152, in ExecuteCommand&#xD;
raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)&#xD;
qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'vim.fault.InvalidLogin'.&#xD;
&#xD;
Error description: (vim.fault.InvalidLogin) {&#xD;

**Comment by alonagetzler** [comment]
irrelevant, cancelling
