### ISSUE TITLE
Non clear error appears when having a wrong VM Resource Pool value

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#279]
Deploy App ended with status Failed with error: 29/Feb/2016 14:54:57 INFO Executing 'vCenter VM From Template' on app 'VM Deployment'...
29/Feb/2016 14:55:02 ERROR Error deploying app VM Deployment. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Error>Script runner exited with exit code: 1: Traceback (most recent call last):&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main&#xD;
"__main__", fname, loader, pkg_name)&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code&#xD;
exec code in run_globals&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\07c095ed-6eb0-48d2-b670-6b8ea5ce6e97\Deploy.zip\__main__.py", line 13, in &lt;module&gt;&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\07c095ed-6eb0-48d2-b670-6b8ea5ce6e97\Deploy.zip\__main__.py", line 10, in main&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\07c095ed-6eb0-48d2-b670-6b8ea5ce6e97\Deploy.zip\driver.py", line 34, in execute&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 5152, in ExecuteCommand&#xD;
raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)&#xD;
qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Exception'.&#xD;
&#xD;
Error description: None&#xD;
&#xD;
[collection is empty]</Error><ErrorCode>100</ErrorCode></Response>
Traceback (most recent call last):
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\yair.z\AppData\Local\Temp\9c439db6-8c7f-4659-9a43-6f55a7abb4e6\Deploy App.zip\__main__.py", line 9, in <module>
File "C:\Users\yair.z\AppData\Local\Temp\9c439db6-8c7f-4659-9a43-6f55a7abb4e6\Deploy App.zip\__main__.py", line 5, in main
File "C:\Users\yair.z\AppData\Local\Temp\9c439db6-8c7f-4659-9a43-6f55a7abb4e6\Deploy App.zip\orchestrator.py", line 22, in execute_app_orchestration

**Comment by doppleware** [comment]
Less important because of autoload validation
