### ISSUE TITLE
Non clear error when having a wrong vCenter address

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#284]
Deploy App ended with status Failed with error: 29/Feb/2016 15:24:53 INFO Executing 'vCenter VM From Template1' on app 'VM Deployment1'...
29/Feb/2016 15:24:58 ERROR Error deploying app VM Deployment1. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Error>Script runner exited with exit code: 1: Traceback (most recent call last):&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main&#xD;
"__main__", fname, loader, pkg_name)&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code&#xD;
exec code in run_globals&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\1015bfe6-3ab4-4cea-b0c3-c3286a5ca4e2\Deploy.zip\__main__.py", line 13, in &lt;module&gt;&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\1015bfe6-3ab4-4cea-b0c3-c3286a5ca4e2\Deploy.zip\__main__.py", line 10, in main&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\1015bfe6-3ab4-4cea-b0c3-c3286a5ca4e2\Deploy.zip\driver.py", line 34, in execute&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 5152, in ExecuteCommand&#xD;
raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)&#xD;
qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'TypeError'.&#xD;
&#xD;
Error description: execute_deploy_from_template() takes exactly 3 arguments (2 given)&#xD;
&#xD;
[collection is empty]</Error><ErrorCode>100</ErrorCode></Response>
Error deploying app VM Deployment1. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Error>Script runner exited with exit code: 1: Traceback (most recent call last):&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main&#xD;
"__main__", fname, loader, pkg_name)&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code&#xD;
exec code in run_globals&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\1015bfe6-3ab4-4cea-b0c3-c3286a5ca4e2\Deploy.zip\__main__.py", line 13, in &lt;module&gt;&#xD;

**Comment by doppleware** [comment]
Priority lowered because of autoload validation
