### ISSUE TITLE
When connecting 3  VM Deployment to one vlan and one of the  VM Deployment isn't deployed the others stops the process of deployment in the middle when deploying using setup script

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#297]
STR
Have an environment with a auto vlan and setup script 
Add three VM Deployment apps to the environment 
connect the three VM Deployment to the vlan 
reserve the environment 

BIR
the VM Deployment are not finshed the deployed process 
* not stable

**Comment by TomerAdmon** [comment]
also happened to me in a simple flow: unstable Setup behavior: 
Logs:

2016-03-10 11:47:16,743 [44] ERROR ResourceManager.TclAPI - [IP: ::1, Machine: QS-IL-TOMERA:8029 - Tcl, QualiSystems Username: admin]
NHibernate.ObjectNotFoundException: No row with the given identifier exists[QualiSystems.ResourceManagement.Service.Domain.ResourceAggragate.LabResource#e334cf25-e43c-4720-90e1-f2df0474be90]

Server stack trace: 
   at NHibernate.Impl.SessionFactoryImpl.DefaultEntityNotFoundDelegate.HandleEntityNotFound(String entityName, Object id)
   at NHibernate.Proxy.AbstractLazyInitializer.CheckTargetState()
   at NHibernate.Proxy.DefaultLazyInitializer.Intercept(InvocationInfo info)
   at LabResourceProxy.get_Name()
   at QualiSystems.ResourceManagement.Service.Domain.TopologyAggregate.ConcreteResourceRequest.get_Alias()
   at (Object , GetterCallback )
   at NHibernate.Tuple.Entity.PocoEntityTuplizer.GetPropertyValues(Object entity)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.GetValues(Object entity, EntityEntry entry, EntityMode entityMode, Boolean mightBeDirty, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.OnFlushEntity(FlushEntityEvent event)
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEntities(FlushEvent event)
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEverythingToExecutions(FlushEvent event)
   at NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   at NHibernate.Impl.SessionImpl.Flush()
   at QualiSystems.Infrastructure.Server.UnitOfWork.NHUnitOfWorkContext.End()
   at QualiSystems.Infrastructure.Server.UnitOfWork.Helpers.UnitOfWorkExtensions.DoInUnitOfWork(IUnitOfWorkProvider unitOfWorkProvider, Action`1 action, Boolean isReadonly)
   at QualiSystems.Infrastructure.Server.Nhibernate.Session.SessionPerRequestProxy`1.WrapInRequestInSession(Object target, MethodBase method, Object[] parameters, Boolean isReadOnly)
   at QualiSystems.Infrastructure.Server.Nhibernate.Session.SessionPerRequestProxy`1.InterceptMethod(Object target, MethodBase method, Object[] parameters)
   at QualiSystems.Infrastructure.Common.Services.SelectiveDynamicProxy`1.OnInvokeMethod(Object target, MethodBase method, Object[] parameters)
   at QualiSystems.Infrastructure.Common.DynamicProxy`1.Invoke(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at QualiSystems.ResourceManagement.Service.APIService.IResourceManagementAPIService.DeployAppToCloudProviderBulk(String reservationId, String[] appNames, DeployAppInput[] commandInputs, Nullable`1 printOutput)

Exception rethrown at [1]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at QualiSystems.ResourceManagement.Service.APIService.IResourceManagementAPIService.DeployAppToCloudProviderBulk(String reservationId, String[] appNames, DeployAppInput[] commandInputs, Nullable`1 printOutput)
   at SyncInvokeDeployAppToCloudProviderBulk(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

**Comment by doppleware** [comment]
Can we retest?

**Comment by TomerAdmon** [comment]
now we got a setup error:

#### server log:
Error: Script runner exited with exit code: 1
Description: Logger File Handler is: C:\Work\Branches\7.0\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\core\logger\../../Logs\6c0d8d8f-146d-4a43-9c5d-db1a7a419a1a\Default--22-Mar-2016--21-14-38.log
Traceback (most recent call last):
  File "C:\Work\Branches\7.0\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\Branches\7.0\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\tomer.a\AppData\Local\Temp\4adce1c2-01c4-403c-9ec6-c8313bf50d43\Default Sandbox Setup.zip\__main__.py", line 8, in 
  File "C:\Users\tomer.a\AppData\Local\Temp\4adce1c2-01c4-403c-9ec6-c8313bf50d43\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Users\tomer.a\AppData\Local\Temp\4adce1c2-01c4-403c-9ec6-c8313bf50d43\Default Sandbox Setup.zip\environment_scripts\profiler\env_profiler.py", line 13, in wrapper
  File "C:\Users\tomer.a\AppData\Local\Temp\4adce1c2-01c4-403c-9ec6-c8313bf50d43\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 31, in execute
  File "C:\Users\tomer.a\AppData\Local\Temp\4adce1c2-01c4-403c-9ec6-c8313bf50d43\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 53, in _try_exeucte_autoload
AttributeError: class AppDeploymentyInfo has no attribute 'LogicalResourceName'

**Comment by TomerAdmon** [comment]
seems OK now. Verified.
