### ISSUE TITLE
When trying to run setup script on environment with more than 15 undeployed apps the setup seems to stuck

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#309]
STR
Have an environmant with 16 undeployed apps with some p2p routes and a setup script
![image](https://cloud.githubusercontent.com/assets/17527106/13451920/ecea56b4-e04b-11e5-88cb-287ad0a18e95.png)
Reserve the enviomnet

BIR
The setup seems to stuck, if you end the reservationyou will be transffered to the 'sorry' page and the VMs will start deploying in the vcenter

**Comment by borismod** [comment]
I assume it depends on the capacity of your execution server. Please try
increasing it to a large number, let's say 60 and run it again.

**Comment by tornizanQ** [comment]
When I'm thinking about it now after that I gain some experience with the app system, I think you are right. I will check it again just to be sure, but maybe in any case we should let the user know that he will need a larger execution server by some kind of error?

It's not very clear that it is goig to need so many command slots

**Comment by alonagetzler** [comment]
it shouldn't get stuck, just work in bulks the size of the capacity of your execution server

**Comment by doppleware** [comment]
can we retest with proper ES capacity?

**Comment by tornizanQ** [comment]
I've tested it know with Es server with 60 command slots, the update finished with active with error statue. When using the same environment with only four apps, its seems to work fine.

This is the error from the activity log that I'm getting:
Error: General
Description: Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
Logger File Handler is: C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\core\logger\../../Logs\a3713acc-3571-4e22-8af7-14b7d3ef3273\Default--16-Mar-2016--08-38-40.log
Traceback (most recent call last):
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\tor.n\AppData\Local\Temp\ff5b7bce-57cc-414e-a496-75f6f794d5e0\Default Sandbox Setup.zip\__main__.py", line 8, in 
  File "C:\Users\tor.n\AppData\Local\Temp\ff5b7bce-57cc-414e-a496-75f6f794d5e0\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Users\tor.n\AppData\Local\Temp\ff5b7bce-57cc-414e-a496-75f6f794d5e0\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 27, in execute
  File "C:\Users\tor.n\AppData\Local\Temp\ff5b7bce-57cc-414e-a496-75f6f794d5e0\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 50, in _deploy_apps_in_reservation
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 2227, in DeployAppToCloudProviderBulk
    return self.generateAPIRequest(OrderedDict([('method_name', 'DeployAppToCloudProviderBulk'), ('reservationId', reservationId), ('appNames', appNames), ('commandInputs', CommonAPIRequest.toContainer(commandInputs)), ('printOutput', printOutput)]))
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 374, in generateAPIRequest
    response_str = self._sendRequest(self.username, self.domain, method_name, request_str)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 1532, in _sendRequest
    return CommonAPISession._sendRequest(self, operation, message, request_headers)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 321, in _sendRequest
    response = urllib23.urlopen(request_object)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: The server encountered an error processing the request. Please see the server logs for more details.

Parameters:

and this is the server logs 
[logs.zip](https://github.com/QualiSystems/vCenterShell/files/175393/logs.zip)
and the Ex server logs:
[LogsEx.zip](https://github.com/QualiSystems/vCenterShell/files/175394/LogsEx.zip)
