### ISSUE TITLE
The deployed vms are not powered off by the teardown script

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#310]
These errors appears:
Error: Script runner exited with exit code: 1
Description: 02/Mar/2016 09:18:13 INFO Executing disconnect routes for reservation a115722f-43ae-42f2-a759-8adf06fd64ab
Traceback (most recent call last):
  File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\yair.z\AppData\Local\Temp\07d6ca5b-5f59-41a1-a051-a7f2793b5776\Default Sandbox Teardown.zip\__main__.py", line 8, in 
  File "C:\Users\yair.z\AppData\Local\Temp\07d6ca5b-5f59-41a1-a051-a7f2793b5776\Default Sandbox Teardown.zip\__main__.py", line 5, in main
  File "C:\Users\yair.z\AppData\Local\Temp\07d6ca5b-5f59-41a1-a051-a7f2793b5776\Default Sandbox Teardown.zip\environment_scripts\env_teardown\teardown_script.py", line 19, in execute
  File "C:\Users\yair.z\AppData\Local\Temp\07d6ca5b-5f59-41a1-a051-a7f2793b5776\Default Sandbox Teardown.zip\environment_scripts\env_teardown\teardown_script.py", line 37, in _disconnect_all_routes_in_reservation
  File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 2020, in DisconnectRoutesInReservation
    return self.generateAPIRequest(OrderedDict([('method_name', 'DisconnectRoutesInReservation'), ('reservationId', reservationId), ('endpoints', CommonAPIRequest.toContainer(endpoints))]))
  File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 340, in generateAPIRequest
    raise CloudShellAPIError(api_result.error_code, api_result.error, response_str)
cloudshell.api.common_cloudshell_api.CloudShellAPIError: CloudShell API error 102: ConnectivityFaultException [Error Code: General] [Original Time: 2016-03-02 09:18:13,589]: No visual connectors found with connected status True

   at QS.TestShell.Server.Connectivity.ConnectivityService.GetVisualConnectorsByConnectivityStatus(Guid[] visualConnectorIds, Boolean connect)

   at QS.TestShell.Server.Connectivity.ConnectivityService.Disconnect(DisconnectRequest disconnectRequest)

   at QS.TestShell.Server.Connectivity.AppsConnectivityHandler.DisconnectAppsByVisualConnectors(Reservation reservation, String[] endpoints)

   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ReservationAPIApplicationService.DisconnectRoutesInReservation(Guid reservationId, String[] endpoints)

Parameters:

Error: General
Description: Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
02/Mar/2016 09:18:13 INFO Executing disconnect routes for reservation a115722f-43ae-42f2-a759-8adf06fd64ab
Traceback (most recent call last):
  File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\yair.z\AppData\Local\Temp\07d6ca5b-5f59-41a1-a051-a7f2793b5776\Default Sandbox Teardown.zip\__main__.py", line 8, in 
  File "C:\Users\yair.z\AppData\Local\Temp\07d6ca5b-5f59-41a1-a051-a7f2793b5776\Default Sandbox Teardown.zip\__main__.py", line 5, in main
  File "C:\Users\yair.z\AppData\Local\Temp\07d6ca5b-5f59-41a1-a051-a7f2793b5776\Default Sandbox Teardown.zip\environment_scripts\env_teardown\teardown_script.py", line 19, in execute
  File "C:\Users\yair.z\AppData\Local\Temp\07d6ca5b-5f59-41a1-a051-a7f2793b5776\Default Sandbox Teardown.zip\environment_scripts\env_teardown\teardown_script.py", line 37, in _disconnect_all_routes_in_reservation
  File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 2020, in DisconnectRoutesInReservation
    return self.generateAPIRequest(OrderedDict([('method_name', 'DisconnectRoutesInReservation'), ('reservationId', reservationId), ('endpoints', CommonAPIRequest.toContainer(endpoints))]))
  File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 340, in generateAPIRequest
    raise CloudShellAPIError(api_result.error_code, api_result.error, response_str)
cloudshell.api.common_cloudshell_api.CloudShellAPIError: CloudShell API error 102: ConnectivityFaultException [Error Code: General] [Original Time: 2016-03-02 09:18:13,589]: No visual connectors found with connected status True

   at QS.TestShell.Server.Connectivity.ConnectivityService.GetVisualConnectorsByConnectivityStatus(Guid[] visualConnectorIds, Boolean connect)

   at QS.TestShell.Server.Connectivity.ConnectivityService.Disconnect(DisconnectRequest disconnectRequest)

   at QS.TestShell.Server.Connectivity.AppsConnectivityHandler.DisconnectAppsByVisualConnectors(Reservation reservation, String[] endpoints)

   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ReservationAPIApplicationService.DisconnectRoutesInReservation(Guid reservationId, String[] endpoints)

Parameters:

**Comment by alexazarh** [comment]
@borismod OR @razaba 
The bug happens because the return result contains duplicate action ids. Something gets mixed in "connect_bulk" in the python driver. Reproduce using environment like this:
http://prntscr.com/aa72s5

**Comment by TomerAdmon** [comment]
error during teardown (P2P scenario)

10/Mar/2016 18:13:57 INFO Executing disconnect routes for reservation 1269f7b4-6648-4244-8d2a-a2f5c7414fe5
10/Mar/2016 18:13:57 ERROR Error disconnecting all routes in reservation 1269f7b4-6648-4244-8d2a-a2f5c7414fe5. Error: CloudShell API error 100: Didn't find any connected connectors. Nothing to disconnect.
10/Mar/2016 18:13:57 INFO Executing 'Delete' on deployed app HAHA_af2b095c in reservation 1269f7b4-6648-4244-8d2a-a2f5c7414fe5
10/Mar/2016 18:13:57 INFO Executing 'Delete' on deployed app HAHA1_94aad2dd in reservation 1269f7b4-6648-4244-8d2a-a2f5c7414fe5
10/Mar/2016 18:14:00 ERROR Error powering off deployed app HAHA_af2b095c in reservation 1269f7b4-6648-4244-8d2a-a2f5c7414fe5. Error: CloudShell API error 104: Command execution failed with error: 'ValueError'.

Error description: Single '}' encountered in format string
10/Mar/2016 18:14:00 ERROR Error powering off deployed app HAHA1_94aad2dd in reservation 1269f7b4-6648-4244-8d2a-a2f5c7414fe5. Error: CloudShell API error 104: Command execution failed with error: 'ValueError'.

Error description: Single '}' encountered in format string
10/Mar/2016 18:14:00 INFO Teardown for reservation 1269f7b4-6648-4244-8d2a-a2f5c7414fe5 completed

**Comment by alexazarh** [comment]
It was caused by a change to the Delete command. Anyway, its fixed again :)

**Comment by TomerAdmon** [comment]
Verified
