### ISSUE TITLE
When reserving an environment with many deployment apps the setup script fail with unclear error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#327]
STR
Have an environment with more than six VM deployment app and a setup script
Reserve the environment 

BIR
No error notification appears but in the activity log there is an unclear fail message:

Error: General
Description: Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
03/Mar/2016 08:17:36 INFO Deploying apps for reservation <cloudshell.api.cloudshell_api.GetReservationDescriptionResponseInfo instance at 0x024CBB70>. App names: VM Deployment, VM Deployment1, VM Deployment2, VM Deployment3, VM Deployment4, VM Deployment5, VM Deployment6, VM Deployment7, VM Deployment8, VM Deployment9
Traceback (most recent call last):
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\tor.n\AppData\Local\Temp\8a0b8e2b-f154-4ac0-960c-4a08b293cc34\Default Sandbox Setup.zip\__main__.py", line 8, in <module>
  File "C:\Users\tor.n\AppData\Local\Temp\8a0b8e2b-f154-4ac0-960c-4a08b293cc34\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Users\tor.n\AppData\Local\Temp\8a0b8e2b-f154-4ac0-960c-4a08b293cc34\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 19, in execute
  File "C:\Users\tor.n\AppData\Local\Temp\8a0b8e2b-f154-4ac0-960c-4a08b293cc34\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 42, in _deploy_apps_in_reservation
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 2215, in ExecuteDeployAppCommandBulk
    return self.generateAPIRequest(OrderedDict([('method_name', 'ExecuteDeployAppCommandBulk'), ('reservationId', reservationId), ('appNames', appNames), ('commandInputs', CommonAPIRequest.toContainer(commandInputs)), ('printOutput', printOutput)]))
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 332, in generateAPIRequest
    response_str = self._sendRequest(self.username, self.domain, method_name, request_str)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 1520, in _sendRequest
    return CommonAPISession._sendRequest(self, operation, message, request_headers)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 279, in _sendRequest
    response = urllib23.urlopen(request_object)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: The server encountered an error processing the request. Please see the server logs for more details.

Parameters:

**Comment by razaba** [comment]
Can we have a reproduction + server logs please?
We need to know if its a deadlock

**Comment by TomerAdmon** [comment]
@tornizanQ  - Tor, we need you here. please try to repreduce and add logs ASAP

**Comment by tornizanQ** [comment]
Cannot reproduce
