### ISSUE TITLE
It's impossible to deploy app using Mono execution server

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#409]

**Comment by Yairzeri** [comment]
![image](https://cloud.githubusercontent.com/assets/17525950/13634389/f42ff5e8-e5fd-11e5-9c19-9adab4c74608.png)

**Comment by Yairzeri** [comment]
![image](https://cloud.githubusercontent.com/assets/17525950/13634400/0460584a-e5fe-11e5-928d-5fbd3b2005fb.png)

**Comment by Yairzeri** [comment]
Logs from QsDriverHost.exe.txt:
2016-03-09 06:48:17,702 [12] WARN  DriverExecutionService - RuntimeErrorConnectorInvocationException exception occurred:
Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/016d401d-a46e-4f2c-8eab-83333c0f8e6f/Default Sandbox Teardown.zip/__main__.py", line 8, in <module>
  File "/tmp/016d401d-a46e-4f2c-8eab-83333c0f8e6f/Default Sandbox Teardown.zip/__main__.py", line 5, in main
  File "/tmp/016d401d-a46e-4f2c-8eab-83333c0f8e6f/Default Sandbox Teardown.zip/environment_scripts/env_teardown/teardown_script.py", line 17, in execute
  File "/usr/lib/python2.7/site-packages/cloudshell/api/cloudshell_scripts_helpers.py", line 25, in get_api_session
    env_details['domain'])
  File "/usr/lib/python2.7/site-packages/cloudshell/api/cloudshell_api.py", line 1516, in __init__
    response_info = self.Logon(username, password, domain)
  File "/usr/lib/python2.7/site-packages/cloudshell/api/cloudshell_api.py", line 2842, in Logon
    return self.generateAPIRequest(OrderedDict([('method_name', 'Logon'), ('username', username), ('password', password), ('domainName', domainName)]))
  File "/usr/lib/python2.7/site-packages/cloudshell/api/common_cloudshell_api.py", line 332, in generateAPIRequest
    response_str = self._sendRequest(self.username, self.domain, method_name, request_str)
  File "/usr/lib/python2.7/site-packages/cloudshell/api/cloudshell_api.py", line 1532, in _sendRequest
    return CommonAPISession._sendRequest(self, operation, message, request_headers)
  File "/usr/lib/python2.7/site-packages/cloudshell/api/common_cloudshell_api.py", line 279, in _sendRequest
    response = urllib23.urlopen(request_object)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

  at CloudShellScriptRunner.ErrorHelper.ThrowGeneralError (System.String description) [0x00000] in <filename unknown>:0 
  at CloudShellScriptRunner.TestShellAPIWrapper.SafelyUseAPI (System.Action useApi, System.String errorMessage, System.Object[] messageParams) [0x00000] in <filename unknown>:0 
  at CloudShellScriptRunner.TestShellAPIWrapper.SafelyUseAPI[String] (System.Func`1 useApi, System.String errorMessage, System.Object[] messageParams) [0x00000] in <filename unknown>:0 
  at CloudShellScriptRunner.TestShellAPIWrapper.WaitForCommandExecutionEnd (Guid executionId) [0x00000] in <filename unknown>:0 
  at CloudShellScriptRunner.SetupTeardownScriptCommandRunner.ExecuteCommand (CommandType commandType) [0x00000] in <filename unknown>:0 
  at CloudShellScriptRunner.CloudShellScriptRunner.Teardown (System.String[,] reservation, System.String[,] globalInputs, System.String[,] requirementsInputs, System.String[,] additionalInfoInputs, System.String[,] connectivityInfo, System.String& out) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0

**Comment by doppleware** [comment]
Solved by @TomerAdmon  to be a Python issue

**Comment by TomerAdmon** [comment]
Verified
