### ISSUE TITLE
deploy P2P (apps) scenario in parallel manualy will fail

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#416]
STR:
1) drag 2 apps to the diagram and connect them
2) execute deploy on both of them

result:
![aa](https://cloud.githubusercontent.com/assets/12639815/13664714/a18c8e3c-e6b1-11e5-8047-444434f9d02c.png)

[416logs.txt](https://github.com/QualiSystems/vCenterShell/files/166833/416logs.txt)

**Comment by TomerAdmon** [comment]
still repreduce, now with diffrant error:

![image](https://cloud.githubusercontent.com/assets/12639815/13751546/5f351314-ea13-11e5-8e7b-e161038469e9.png)

2016-03-14 18:33:24,023 [38] ERROR ResourceManager.TclAPI - [IP: ::1, Machine: QS-IL-TOMERAD:8029 - Tcl, QualiSystems Username: admin]
Error retrieving resource: Photon_Tomer1 - EntityException [Error Code: EntityNotFound]: Entity 'Photon_Tomer1' not found.
   at QualiSystems.Infrastructure.Hierarchy.Service.Core.ExceptionsUtil.ThrowInvalidEntityOperationException(ErrorCode errorCode, String[] formatArgs)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByFullPath(String fullPath)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByNameOrPath(String entityFullName)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.TryGetLabResourceByFullName(String resourceFullName, LabResource& labResource, String& errorMessage)
2016-03-14 18:33:24,070 [38] ERROR ResourceManager.TclAPI - [IP: ::1, Machine: QS-IL-TOMERAD:8029 - Tcl, QualiSystems Username: admin]
Error retrieving resource: Photon_Tomer1 - EntityException [Error Code: EntityNotFound]: Entity 'Photon_Tomer1' not found.
   at QualiSystems.Infrastructure.Hierarchy.Service.Core.ExceptionsUtil.ThrowInvalidEntityOperationException(ErrorCode errorCode, String[] formatArgs)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByFullPath(String fullPath)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByNameOrPath(String entityFullName)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.TryGetLabResourceByFullName(String resourceFullName, LabResource& labResource, String& errorMessage)
2016-03-14 18:33:24,522 [ZeroMQ server worker thread] ERROR QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver - [Machine: QS-IL-TOMERAD, Domain Username: Tomer.a]
System.NullReferenceException: Object reference not set to an instance of an object.
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ResourceNameRetriever.GetResourceName(Guid resourceId)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.FailedExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.InstantJobEventsLogExecutionObserver.ExecutionEnded(IInstantJob instantJob, Execution execution, ExecutionResult executionResult)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.<>c__DisplayClassa.<ExecutionEnded>b__9(IInstantJobExecutionObserver x)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.SafelyDoOnEachObserver(Action`1 action, Execution execution, IInstantJob instantJob)
2016-03-14 18:33:24,522 [ZeroMQ server worker thread] WARN  DistributedProvisioning.Execution - [Machine: QS-IL-TOMERAD, Domain Username: Tomer.a]
Resource Command 'deploy' Failed, Resource Id: '70a04749-7013-4640-8b7b-f508dc0daefc', Reservation Id 'd60e5247-fa3f-4c2f-a1d1-35aef5f020e3', Execution Id: '0c9705c6-b67f-4dde-bdd8-70ebb22a8603', Owner 'admin', Execution Server: 'QS-IL-TOMERAD', Output: 'Failed with error: 'Unable to locate Photon_Tomer1''
2016-03-14 18:33:46,538 [ZeroMQ server worker thread] ERROR QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver - [Machine: QS-IL-TOMERAD, Domain Username: Tomer.a]
System.NullReferenceException: Object reference not set to an instance of an object.
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ResourceNameRetriever.GetResourceName(Guid resourceId)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompletedExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.InstantJobEventsLogExecutionObserver.ExecutionEnded(IInstantJob instantJob, Execution execution, ExecutionResult executionResult)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.<>c__DisplayClassa.<ExecutionEnded>b__9(IInstantJobExecutionObserver x)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.SafelyDoOnEachObserver(Action`1 action, Execution execution, IInstantJob instantJob)

**Comment by alexazarh** [comment]
I can not reproduce

**Comment by TomerAdmon** [comment]
seems to be fixed
