### ISSUE TITLE
Setup script is not deploying apps and finish with active with error statue

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#436]
STR
Have an environment with setup script and setup and teardown driver
Add an undeployed app from template \ image 
Reserve the environment

BIR
Setup is fail, the reservation is Active with error
The undeployed app is still undeployed.

** the bug is stable and the app can be deployed successfully by manually run the deploy command
 
Error from activity log:

Error: General
Description: Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
Traceback (most recent call last):
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\tor.n\AppData\Local\Temp\7d0b699c-1a91-43d7-841e-8a6723503cee\Default Sandbox Setup.zip\__main__.py", line 1, in 
  File "C:\Users\tor.n\AppData\Local\Temp\7d0b699c-1a91-43d7-841e-8a6723503cee\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 5, in 
ImportError: No module named vCenterShell.common.logger

Parameters:

Server Logs:
[Logs.zip](https://github.com/QualiSystems/vCenterShell/files/171185/Logs.zip)

Ex logs:
[Logs.zip](https://github.com/QualiSystems/vCenterShell/files/171187/Logs.zip)

**Comment by TomerAdmon** [comment]
Verified
