### ISSUE TITLE
Deploy from template failed on 192.168.26.25

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#488]
### STR
1) autoload the vcenter (192.168.26.25)
2) try to deploy a vm

### Result:
Can't deploy with this error:
![image](https://cloud.githubusercontent.com/assets/12639815/13851291/42894834-ec66-11e5-8700-ded615635f88.png)

**Comment by doppleware** [comment]
Can you include the details you used to autoload it?

**Comment by doppleware** [comment]
@TomerAdmon  also python logs!

**Comment by TomerAdmon** [comment]
Execution server logs:
2016-03-20 11:47:06,357 [29] ERROR DefaultProcessCreator - Subprocess error: You are using pip version 8.0.2, however version 8.1.1 is available.
2016-03-20 11:47:06,358 [29] ERROR DefaultProcessCreator - Subprocess error: You should consider upgrading via the 'python -m pip install --upgrade pip' command.
2016-03-20 11:47:12,157 [32] ERROR DefaultProcessCreator - Subprocess error: You are using pip version 8.0.2, however version 8.1.1 is available.
2016-03-20 11:47:12,157 [32] ERROR DefaultProcessCreator - Subprocess error: You should consider upgrading via the 'python -m pip install --upgrade pip' command.
2016-03-20 11:47:13,516 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:13 INFO action:START command_name:execute_deploy_from_template
2016-03-20 11:47:14,279 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 INFO connecting to vcenter: 192.168.26.25
2016-03-20 11:47:14,280 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 DEBUG connection params: host: 192.168.26.25 username: administrator@vsphere.local port: 443
2016-03-20 11:47:14,282 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 INFO Starting new HTTPS connection (1): 192.168.26.25
2016-03-20 11:47:14,295 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 DEBUG "GET //sdk/vimServiceVersions.xml HTTP/1.1" 200 430
2016-03-20 11:47:14,475 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 INFO connected to vcenter: 192.168.26.25
2016-03-20 11:47:14,475 [33] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 INFO executing command: execute_deploy_from_template
2016-03-20 11:47:14,475 [33] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 DEBUG command params: 'vim.ServiceInstance:ServiceInstance',<cloudshell.cp.vcenter.models.DeployDataHolder.DeployDataHolder object at 0x03AEC4B0>,<infrastructure.contracts.drivercontext.ResourceContextDetails instance at 0x03AEDA80>
2016-03-20 11:47:14,620 [33] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 ERROR error has occurred while executing command: execute_deploy_from_template
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 ERROR Could not find Cluster or Resource Pool by the names: "Cluster", ""
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error: Traceback (most recent call last):
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\common\wrappers\command_wrapper.py", line 88, in execute_command_with_connection
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:     results = command(*tuple(command_args))
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\commands\deploy_vm.py", line 20, in execute_deploy_from_template
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:     deploy_result = self.deployer.deploy_from_template(si, deployment_params, resource_context)
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\vm\deploy.py", line 56, in deploy_from_template
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:     clone_vm_result = self.pv_service.clone_vm(params)
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\common\vcenter\vmomi_service.py", line 397, in clone_vm
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:     resource_pool = self._get_resource_pool(clone_params)
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\common\vcenter\vmomi_service.py", line 463, in _get_resource_pool
2016-03-20 11:47:14,621 [23] ERROR DefaultProcessCreator - Subprocess error:     clone_params.resource_pool))
2016-03-20 11:47:14,622 [23] ERROR DefaultProcessCreator - Subprocess error: ValueError: Could not find Cluster or Resource Pool by the names: "Cluster", ""
2016-03-20 11:47:14,622 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 INFO disconnecting from vcenter: 192.168.26.25
2016-03-20 11:47:14,636 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 INFO action:END command_name:execute_deploy_from_template
2016-03-20 11:47:14,636 [23] ERROR DefaultProcessCreator - Subprocess error: 20/Mar/2016 11:47:14 ERROR Customer's driver raised an exception:
2016-03-20 11:47:14,636 [23] ERROR DefaultProcessCreator - Subprocess error: Traceback (most recent call last):
2016-03-20 11:47:14,636 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\QsPythonDriverHost\execution\instance_loader.py", line 134, in invoke_func
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:     result = driver_func(**args)
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:   File "c:\users\tomer.a\appdata\local\temp\tmpk3cduv.zip_env\driver.py", line 52, in deploy_from_template
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:     return self.command_orchestrator.deploy_from_template(context, deploy_data)
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\commands\command_orchestrator.py", line 157, in deploy_from_template
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:     context.resource)
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\common\wrappers\command_wrapper.py", line 88, in execute_command_with_connection
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:     results = command(*tuple(command_args))
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\commands\deploy_vm.py", line 20, in execute_deploy_from_template
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:     deploy_result = self.deployer.deploy_from_template(si, deployment_params, resource_context)
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\vm\deploy.py", line 56, in deploy_from_template
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:     clone_vm_result = self.pv_service.clone_vm(params)
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\common\vcenter\vmomi_service.py", line 397, in clone_vm
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:     resource_pool = self._get_resource_pool(clone_params)
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:   File "C:\ProgramData\QualiSystems\venv\VCenter_Shell_Driver_1_6\lib\site-packages\cloudshell\cp\vcenter\common\vcenter\vmomi_service.py", line 463, in _get_resource_pool
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error:     clone_params.resource_pool))
2016-03-20 11:47:14,637 [23] ERROR DefaultProcessCreator - Subprocess error: ValueError: Could not find Cluster or Resource Pool by the names: "Cluster", ""

**Comment by TomerAdmon** [comment]
@doppleware  - this is currently blocking us from working on this Vcenter. can someone research it ASAP?

**Comment by TomerAdmon** [comment]
Autoload was made without any parameter rather then HOLDING NETWORK = "VM Network"

**Comment by TomerAdmon** [comment]
seems to be fixed.
