### ISSUE TITLE
P2V scenario - Two apps and one Vlan

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#540]
### STR
1) connect two undeployed apps to vlan auto
2) click deploy app on the first
3) wait 2 sec
3) click deploy app on the secoun

### Result:
Only one of the apps will be deployed
![image](https://cloud.githubusercontent.com/assets/12639815/13955951/60cf0f58-f04f-11e5-8dda-3233d75cb662.png)

### Error:
![image](https://cloud.githubusercontent.com/assets/12639815/13955890/272748ce-f04f-11e5-8e2a-2b7e52ed09a2.png)

Server logs:
2016-03-22 16:54:12,344 [50] ERROR ResourceManager.TclAPI - [IP: ::1, Machine: QS-IL-TOMERAD:8029 - Tcl, QualiSystems Username: admin]
Error retrieving resource: VLAN Auto - EntityException [Error Code: EntityNotFound]: Entity 'VLAN Auto' not found.
   at QualiSystems.Infrastructure.Hierarchy.Service.Core.ExceptionsUtil.ThrowInvalidEntityOperationException(ErrorCode errorCode, String[] formatArgs)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByFullPath(String fullPath)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByNameOrPath(String entityFullName)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.TryGetLabResourceByFullName(String resourceFullName, LabResource& labResource, String& errorMessage)

**Comment by doppleware** [comment]
Its probably because the same of the VLAN changes....

**Comment by alexazarh** [comment]
1) I couldnt reproduce the problem
2) The logs from the server are not related to the deployment error, during deployment we dont look at connected resources. 
3) We need the logs from the execution server t understand what happend during deployment

**Comment by TomerAdmon** [comment]
After quick talk with Alex, seems like rare concurrency issue. the API request sent with the "Auto Vlan" name when the other app connects and change the name to "VLAN 2". this scenario is rare and can be fixed in the future using guids and not names.
