### ISSUE TITLE
Setup script tries to power up physical devices

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#573]
### Issue details

Environment with DUT and setup script tries to perform power on the dut

### Steps to reproduce

Have an environment with a single DUT, and the setup script, reserve it

Defect is reproduced if setup fails with error that:
Exception: Reservation is Active with Errors - Error powering on deployed app DUT1/Blade 1/Port 10

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by nahumtimerman** [comment]
Error: Script runner exited with exit code: 1
Description: Logger File Handler is: C:\work\7.0\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\core\logger\../../Logs\da9f5998-ae4a-4061-b79e-857032e1d193\Default--27-Mar-2016--19-42-07.log
Traceback (most recent call last):
  File "C:\work\7.0\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\work\7.0\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\nahum-t\AppData\Local\Temp\c0c665a2-15a8-4b33-8670-f194e4e92d03\Default Sandbox Setup.zip\__main__.py", line 8, in 
  File "C:\Users\nahum-t\AppData\Local\Temp\c0c665a2-15a8-4b33-8670-f194e4e92d03\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Users\nahum-t\AppData\Local\Temp\c0c665a2-15a8-4b33-8670-f194e4e92d03\Default Sandbox Setup.zip\environment_scripts\profiler\env_profiler.py", line 13, in wrapper
  File "C:\Users\nahum-t\AppData\Local\Temp\c0c665a2-15a8-4b33-8670-f194e4e92d03\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 44, in execute
  File "C:\Users\nahum-t\AppData\Local\Temp\c0c665a2-15a8-4b33-8670-f194e4e92d03\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 169, in _run_async_power_on_refresh_ip_install
Exception: Reservation is Active with Errors - Error powering on deployed app DUT1

Parameters:

**Comment by nahumtimerman** [comment]
fixed
