### ISSUE TITLE
Concurrent teardown of two reservations can be very slow under certain circumstances

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#581]
### Issue details

Concurrent teardown of two reservations can be very slow under certain circumstances

### Steps to reproduce

You have a topology with 15~ apps, each of which autoloads 10 ports.
You reserve two such topologies.
All apps are deployed and autoloaded successfully

Now you end both reservations.
Even though vcenter very quickly deletes the VMs, teardown keeps running and running.
Behind the scenes, testshell server throws multiple errors on ResourceLockingServiceFaultException - timeout expired for ResourceManagementDomainService.DeleteResource()

Seems like these errors are getting throwed sequentially... maybe we should consider having a bulk delete resource command...

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by nahumtimerman** [comment]
2016-03-28 16:26:05,488 [10] ERROR ResourceManager.TclAPI - [IP: ::1, Machine: QS-IL-NAHUMT2:8029 - Tcl, QualiSystems Username: admin]
Error deleting resource Template13_64aa1800 - ResourceLockingServiceFaultException [Error Code: General] [Original Time: 2016-03-28 16:26:05,486]: The wait operation timed out

Server stack trace: 


Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at QualiSystems.Infrastructure.Hierarchy.Service.Core.IEntityDataHandler.Delete(EntityBase entity, EntityDataHandlerState state)

Exception rethrown at [1]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at QualiSystems.Infrastructure.Hierarchy.Service.Core.IEntityDataHandler.Delete(EntityBase entity, EntityDataHandlerState state)
   at QualiSystems.Infrastructure.Hierarchy.Service.HierarchyService.DeleteEntity(EntityDTO entityDTO)

Exception rethrown at [2]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at QualiSystems.Contracts.Hierarchy.IHierarchyService.DeleteEntity(EntityDTO entityDTO)

Exception rethrown at [3]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at QualiSystems.Contracts.Hierarchy.IHierarchyService.DeleteEntity(EntityDTO entityDTO)
   at QualiSystems.ResourceManagement.Service.DomainService.ResourceManagementDomainService.DeleteResource(ResourceDTO resource)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.EntityManagementAPIApplicationService.<>c__DisplayClass79.<DeleteResourcesInternal>b__75(IUnitOfWorkContext ctx)
   at QualiSystems.Infrastructure.Server.UnitOfWork.Helpers.UnitOfWorkExtensions.DoInNewUnitOfWork(IUnitOfWorkProvider unitOfWorkProvider, Action`1 action, Boolean isReadonly)
   at QualiSystems.Infrastructure.Server.UnitOfWork.UnitOfWork.DoInNewUnitOfWork(Action`1 action, Boolean isReadonly)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.EntityManagementAPIApplicationService.DeleteResourcesInternal(IEnumerable`1 resourcesFullPath)

**Comment by nahumtimerman** [comment]
[TeamServer.Service - Copy.txt](https://github.com/QualiSystems/vCenterShell/files/191835/TeamServer.Service.-.Copy.txt)

**Comment by nahumtimerman** [comment]
Path to environment:
"\\qsnas1\shared\Nahum\Environments\Virtualization\The Many Faces of Koprach.zip"

**Comment by nahumtimerman** [comment]
Associated bug;
http://team:8080/tfs/web/wi.aspx?pcguid=7f0f1432-0cbe-43ca-b805-7a63763a5206&id=152527

**Comment by nahumtimerman** [comment]
fixed, yay
