### ISSUE TITLE
When deploying an app while selecting to use a model that has a driver with no autoload command, exception occurs during deployment

### ISSUE THREAD

**Issue by LeeorV** [QualiSystems/vCenterShell#645]
When deploying an app while selecting to use a model that has a driver with no autoload command, exception occurs during deployment.

Screenshot:
\\qsnas1\Shared\LeeorV\Bug Info\autoload_fail.png

Server Log
2016-04-13 10:37:46,574 [87] ERROR ResourceManager.TclAPI - [IP: 192.168.41.46, Machine: QS-SRV-SBEXECUS:8029 - Tcl, QualiSystems Username: admin]
Windows 10 Clean VM_b16c4f3f: The selected resource driver does not contain 'GetInventory' function and is not valid for Auto Load

Execution Server Log:
2016-04-13 12:21:50,436 - application - InstanceLoader - ERROR - Customer's driver raised an exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\QualiSystems\TestShell\ExecutionServer\QsPythonDriverHost\execution\instance_loader.py", line 134, in invoke_func
    result = driver_func(**args)
  File "c:\windows\temp\tmpid2t_o.zip_env\orchestrator.py", line 41, in deploy
    self._try_execute_autoload(session, reservation_id, deployment_result.LogicalResourceName, logger)
  File "c:\windows\temp\tmpid2t_o.zip_env\orchestrator.py", line 214, in _try_execute_autoload
    session.AutoLoad(deployed_app_name)
  File "C:\ProgramData\QualiSystems\venv\Deployment_Orchestrator_3_8\lib\site-packages\cloudshell\api\cloudshell_api.py", line 1722, in AutoLoad
    return self.generateAPIRequest(OrderedDict([('method_name', 'AutoLoad'), ('resourceFullPath', resourceFullPath)]))
  File "C:\ProgramData\QualiSystems\venv\Deployment_Orchestrator_3_8\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 382, in generateAPIRequest
    raise CloudShellAPIError(api_result.error_code, api_result.error, response_str)
CloudShellAPIError: CloudShell API error 100: AutoLoad failed.

Windows 10 Clean VM_640a2e89: The selected resource driver does not contain 'GetInventory' function and is not valid for Auto Load

**Comment by alexazarh** [comment]
Opened bug #152796 in tfs.

**Comment by tornizanQ** [comment]
Still reproduce on 7.1 
With simpler error notification
"Deploy App ended with status Failed with error: AutoLoad failed.
Deploy From Template_709f500b: The selected resource driver does not contain 'GetInventory' function and is not valid for Auto Load"

**Comment by tornizanQ** [comment]
Fixed on 7.1 
Reproduces on 7.0.0.8351
