### ISSUE TITLE
setup fails when a static VM is connected to a vcenter  app

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#775]
STR
Have environment with setup script 
Add vcenter deploy from temp app
Add a Static VM
Connect them with CVC
Reserve the environment 

BIR
The connection is not establish and the setup fails with error:
"Error: General
Description: Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
Traceback (most recent call last):
  File "C:\Program Files (x86)\QualiSystems\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Program Files (x86)\QualiSystems\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\WINDOWS\TEMP\77ac39df-513b-4407-a5a4-ab29c8d0273e\Default Sandbox Setup.zip\__main__.py", line 8, in 
  File "C:\WINDOWS\TEMP\77ac39df-513b-4407-a5a4-ab29c8d0273e\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\WINDOWS\TEMP\77ac39df-513b-4407-a5a4-ab29c8d0273e\Default Sandbox Setup.zip\sandbox_scripts\profiler\env_profiler.py", line 13, in wrapper
  File "C:\WINDOWS\TEMP\77ac39df-513b-4407-a5a4-ab29c8d0273e\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 50, in execute
  File "C:\WINDOWS\TEMP\77ac39df-513b-4407-a5a4-ab29c8d0273e\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 181, in _connect_all_routes_in_reservation
  File "C:\WINDOWS\TEMP\77ac39df-513b-4407-a5a4-ab29c8d0273e\Default Sandbox Setup.zip\sandbox_scripts\helpers\resource_helpers.py", line 37, in is_deployed_app_or_descendant_of_deployed_app
KeyError: 'Six'

Parameters:"

Logs
[QsDriverHost.exe.txt]
(https://github.com/QualiSystems/vCenterShell/files/432519/QsDriverHost.exe.txt)

**Comment by tornizanQ** [comment]
Old version
